### ISSUE TITLE
Source manuscripts / images canonical links

### ISSUE THREAD

**Issue by PonteIneptique** [HTR-United/schema#15]
@alix-tz What do you think we add a new feature for linking original sources such as:

```yaml
sources: 
  - Link 1
  - Link 2
  - Link 3
```

I'd make it a list of list (to allow for multiple links per source) or a list of string (single link per source)

**Comment by PonteIneptique** [comment]
More complex could be a dictionary:

```yaml
- name: BnF Latin 82367
  links:
    - URL1
    - URL2
 ```

But it feels probably bloated ?

Other option:


```yaml
- name: BnF Latin 82367
  manifest: URI1 #Optional
  links: 
    - URI2
    - URI3
    - URI4
 ```
